# Generated by Django 4.1.7 on 2023-04-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPost',
            fields=[
                ('city', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=37, primary_key=True, serialize=False)),
                ('warehouses', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('isAreaCenter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('offer', models.TextField(verbose_name='Замовлення')),
                ('amount', models.CharField(max_length=255, verbose_name='Ціна')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефону')),
                ('area', models.CharField(max_length=255, verbose_name='Область')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Пункт видачі')),
            ],
        ),
        migrations.CreateModel(
            name='Podik',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('available', models.BooleanField(verbose_name='Доступність')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('currencyId', models.CharField(max_length=255, verbose_name='Валюта')),
                ('categoryId', models.IntegerField(verbose_name='Id категорії')),
                ('vendorCode', models.IntegerField()),
                ('quantity_in_stock', models.IntegerField(verbose_name='Кількість товару склад')),
                ('url', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255, verbose_name='URL картинки')),
                ('param', models.TextField(null=True)),
                ('flavour', models.CharField(max_length=255, null=True, verbose_name='Выбор вкуса')),
                ('nicotine_strength', models.CharField(max_length=255, null=True, verbose_name='Крепость никотина')),
                ('fluid_volume', models.CharField(max_length=255, null=True, verbose_name='Объем жидкости')),
                ('battery_capacity', models.CharField(max_length=255, null=True, verbose_name='Ёмкость аккумулятора')),
                ('cartridge_capacity', models.CharField(max_length=255, null=True, verbose_name='Объём картриджа')),
                ('resistance', models.CharField(max_length=255, null=True, verbose_name='Выбор сопротивления')),
                ('power', models.CharField(max_length=255, null=True, verbose_name='Мощность')),
                ('atomizer_volume', models.CharField(max_length=255, null=True, verbose_name='Объем атомайзера')),
                ('max_power', models.CharField(max_length=255, null=True, verbose_name='Максимальная мощность')),
                ('puffs_number', models.CharField(max_length=255, null=True, verbose_name='Количество затяжек')),
                ('rechargeable', models.BooleanField(null=True, verbose_name="Перезаряжаемые'")),
                ('compatibility_selection', models.CharField(max_length=255, null=True, verbose_name='Выбор совместимости')),
            ],
            options={
                'verbose_name': 'Електронна цигарка',
                'verbose_name_plural': 'Електронні цигарки',
                'ordering': ['categoryId', 'name'],
            },
        ),
    ]
