# Generated by Django 4.1.7 on 2023-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='products',
            field=models.TextField(null=True),
        ),
    ]
