# Generated by Django 4.1.7 on 2023-04-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_novapost_mailboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='comment',
            field=models.TextField(null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='offers',
            name='delivery_method',
            field=models.CharField(max_length=255, null=True, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='offers',
            name='payment_method',
            field=models.CharField(max_length=255, null=True, verbose_name='Спосіб оплати'),
        ),
    ]
