# Generated by Django 4.1.7 on 2023-04-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_offers_comment_offers_delivery_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефону')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
            ],
        ),
    ]
