# Generated by Django 4.1.7 on 2023-04-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
