# Generated by Django 4.1.7 on 2023-04-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_offers_options_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_id',
            field=models.IntegerField(null=True),
        ),
    ]
