# Generated by Django 4.1.7 on 2023-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_offers_offer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва фільтру')),
                ('value', models.CharField(max_length=255, verbose_name='Значення фільтру')),
            ],
            options={
                'verbose_name': 'Фільтр',
                'verbose_name_plural': 'Фільтри',
            },
        ),
    ]
