# Generated by Django 4.1.7 on 2023-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podik',
            name='atomizer_volume',
            field=models.CharField(max_length=255, null=True, verbose_name='Обсяг атомайзера'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='battery_capacity',
            field=models.CharField(max_length=255, null=True, verbose_name='Ємність акумулятора'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='cartridge_capacity',
            field=models.CharField(max_length=255, null=True, verbose_name="Об'єм картриджа"),
        ),
        migrations.AlterField(
            model_name='podik',
            name='compatibility_selection',
            field=models.CharField(max_length=255, null=True, verbose_name='Вибір сумісності'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='flavour',
            field=models.CharField(max_length=255, null=True, verbose_name='Вибір смаку'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='fluid_volume',
            field=models.CharField(max_length=255, null=True, verbose_name='Обсяг рідини'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='max_power',
            field=models.CharField(max_length=255, null=True, verbose_name='Максимальна потужність'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='nicotine_strength',
            field=models.CharField(max_length=255, null=True, verbose_name='Міцність нікотину'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='power',
            field=models.CharField(max_length=255, null=True, verbose_name='Потужність'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='puffs_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Кількість затяжок'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='rechargeable',
            field=models.BooleanField(null=True, verbose_name="Перезаряджаються'"),
        ),
        migrations.AlterField(
            model_name='podik',
            name='resistance',
            field=models.CharField(max_length=255, null=True, verbose_name='Вибір опору'),
        ),
    ]
