# Generated by Django 4.1.7 on 2023-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_filters_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral_count',
            field=models.CharField(max_length=255, null=True, verbose_name='Кількість рефералів'),
        ),
        migrations.AddField(
            model_name='users',
            name='tg_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Id користувача'),
        ),
    ]
