# Generated by Django 4.1.7 on 2023-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_users_referral_count_users_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='tg_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
