# Generated by Django 4.1.7 on 2023-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_offers_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas_and_costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Область')),
                ('cost', models.IntegerField(verbose_name='Ціна за доставку')),
            ],
        ),
    ]
