# Generated by Django 4.1.7 on 2023-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_areas_and_costs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas_and_costs',
            options={'verbose_name': 'Ціна за доставку', 'verbose_name_plural': 'Ціни за доставку'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Користувач бота', 'verbose_name_plural': 'Користувачі бота'},
        ),
        migrations.RemoveField(
            model_name='filters',
            name='value',
        ),
        migrations.AddField(
            model_name='filters',
            name='visible',
            field=models.BooleanField(null=True, verbose_name='Доступність'),
        ),
    ]
