# Generated by Django 4.1.7 on 2023-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_areas_and_costs_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='message_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Надіслати повідомлення'),
        ),
    ]
