# Generated by Django 4.1.7 on 2023-05-01 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_cashbackpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Процент кешбека')),
            ],
            options={
                'verbose_name': 'Процент кешбека',
                'verbose_name_plural': 'Процент кешбека',
            },
        ),
    ]
