# Generated by Django 4.1.7 on 2023-05-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_paymentmethod_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='visible',
            field=models.BooleanField(default=True, null=True, verbose_name='Доступність'),
        ),
    ]
