# Generated by Django 4.1.7 on 2023-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_filters_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='notifications',
            field=models.TextField(default=''),
        ),
    ]
