# Generated by Django 4.1.7 on 2023-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_users_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='notifications',
        ),
        migrations.AddField(
            model_name='offers',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
