# Generated by Django 4.1.7 on 2023-05-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_users_notifications_offers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='podik',
            name='subscribers',
            field=models.TextField(null=True),
        ),
    ]
