# Generated by Django 4.1.7 on 2023-05-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_podik_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Спосіб оплати', 'verbose_name_plural': 'Способи оплати'},
        ),
    ]
