# Generated by Django 4.1.7 on 2023-05-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_paymentmethod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='podik',
            name='disposable_flavour',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='podik',
            name='elf_bar_flavour',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='podik',
            name='hqd_flavour',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='podik',
            name='liquids_flavour',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='podik',
            name='ukrainian_flavour',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
